# Generated by Django 6.0.5 on 2026-05-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.CharField(default='general', max_length=32)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='results/originals/')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='results/annotated/')),
                ('heatmap_image', models.ImageField(blank=True, null=True, upload_to='results/heatmaps/')),
                ('health_score', models.FloatField(default=0.0)),
                ('condition', models.CharField(default='Unknown', max_length=32)),
                ('estimated_life_years', models.FloatField(default=0.0)),
                ('critical', models.BooleanField(default=False)),
                ('crack_score', models.FloatField(default=0.0)),
                ('seep_score', models.FloatField(default=0.0)),
                ('surface_score', models.FloatField(default=0.0)),
                ('crack_area_pct', models.FloatField(default=0.0)),
                ('seep_area_pct', models.FloatField(default=0.0)),
                ('num_crack_regions', models.IntegerField(default=0)),
                ('num_seep_regions', models.IntegerField(default=0)),
                ('largest_crack_mm_eq', models.FloatField(default=0.0)),
                ('ai_used', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('warnings', models.TextField(blank=True, default='')),
                ('recommendations', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'ScanResult',
                'ordering': ['-created_at'],
            },
        ),
    ]
